Main after audit v2 (#153)
* Deploy as one of the owners and transfer factory to safe

* Erc20 factory deposit (#151)

* feat: erc20 deposit function for factory

* feat: test for erc20 factory deposit

* refactor: add depositERC20 to factory interface

* add external pool-buy filter

- can be used to implement dynamic flagged / marked NFTs
- allow set external token filter on creation
- factory allowed to change external filter
- allow setting 0 address to reset external filter
- add validate (all) curve params, helps reduce CollectionPool size
- emits events on set

---------

Co-authored-by: Plant More Trees <trees@are.nice>
Co-authored-by: potato-cat69 <pack_yak1@hotmail.com>

* better error/job handling for parallel forge test

- native bash job handling rather than using xargs

* refactor: expose externalFilter view in interface

* refactor: expose filtered pool creation methods

* fix: change min price of exponential curve to 100

- 1 gwei was too high for reasonable usdc pools

* fix: function signature in foundry test

* fix lint for tests and enable safe deployment for mainnet

---------

Co-authored-by: Modest Cowboy <114374538+modest-cowboy@users.noreply.github.com>
Co-authored-by: edf0124514b214e7337f87c7a8e5b679df <114981095+edf0124514b214e7337f87c7a8e5b679df@users.noreply.github.com>
Co-authored-by: Plant More Trees <trees@are.nice>

diff --git a/scripts/forge-test-parallel b/scripts/forge-test-parallel
--- a/scripts/forge-test-parallel
+++ b/scripts/forge-test-parallel
@@ -1,22 +1,73 @@
 #!/bin/bash
 
+## Runs forge tests in parallel. All parameters are passed to `forge test`.
+## Run with JOBS=N to specify maximum number of concurrent jobs
+
+# kill process group if ctrl-c
+trap "kill -9 0" SIGINT
+
+# start time in nanoseconds
+START=$(date +%s%N)
+
 # fast profile in foundry.toml has less optimizations
 export FOUNDRY_PROFILE=fast
 
-# use all cores
-CORES=`nproc`
-echo "$CORES cores detected"
+if [ -z "$JOBS" ]; then
+  JOBS=`nproc`
+  printf "Using all $JOBS cores"
+else
+  printf "Using $JOBS concurrent subprocesses"
+fi
+
+# runs and buffers `forge test`, aborts all if anything fails
+forge_test() {
+  printf .
+
+  # buffer output so it's not all mingled
+  OUTPUT=`forge test --silent --match-path "$*"`
+
+  if (( $? == 0 )); then
+    # OK
+    echo
+    echo "$OUTPUT"
+  else
+    # Error
+    echo
+    echo "$OUTPUT"
+    echo "At least one sub-test had errors, aborting"
+    kill -9 0 # kill process group
+  fi
+}
 
 # test all but test-cases
-forge test --silent --match-path "*/foundry/filter/*.t.sol" $* &
-forge test --silent --match-path "*/foundry/bonding-curve-tests/*.t.sol" $* &
+( forge_test '*/foundry/filter/*.t.sol' $* )&
+( forge_test '*/foundry/bonding-curve-tests/*.t.sol' $* )&
 
-# test test-cases
 cd $(dirname -- "$0")/../test/foundry/test-cases
-find *.t.sol | # find all tests
-  paste -d, - - - - - - - - | # 4 files at a time
-  xargs -P $CORES -I _ forge test --silent --match-path "*/{_}*" $*
 
-# in case first 2 tests are still running
-fg 2&> /dev/null
-fg 2&> /dev/null
+# note that test-cases/ files must not have spaces
+TEST_CASES=`
+  find *.t.sol | # find all tests
+  paste -d, - - - - - - - - # 4 files at a time
+`
+
+for TEST_CASE in $TEST_CASES; do
+  # PIDs of running jobs, converted to array
+  RUNNING=(`jobs -pr`)
+
+  if (( ${#RUNNING[@]} >= JOBS )); then
+    wait -n # wait for earlier background job to finish
+  fi
+
+  # first parameter is absolute-path glob matching some test files only
+  # pass through rest of script parameters
+  (
+    forge_test "*/{$TEST_CASE}*" #$*
+  )& # run in background as subshell
+done
+
+# wait for all background jobs to finish
+wait
+
+END=$(date +%s%N)
+printf "Total time: %.1fs\n" $((END-START))e-9
